# action.yml
name: 'Jupyterbook Action'
description: 'Render and Publish a Jupyterbook'
inputs:
  generatefile:  # iPynb to generate
    description: 'iPynb to generate'
    required: true
    default: 'generate_files_ipynb'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.generatefile }}